### ISSUE TITLE
add "hactober-accepted" label on all merged PR

### ISSUE THREAD

**Issue by anjali1102** [ALLINONE4298/Hacktober2020#14]
else everyone's Merged PRs will not be counted by hacktober

**Comment by ALLINONE4298** [comment]
"hacktoberfest-accepted" label not required.
as this repo already have hacktoberfest topic tag.

READ THIS OFFICIAL STATEMENT FROM DIGITAL OCEAN
![bandicam 2020-10-13 16-59-42-519](https://user-images.githubusercontent.com/72457759/95855196-a4abf680-0d75-11eb-974d-97f79ed06181.jpg)
